### ISSUE TITLE
### Calling <<-EOS.undent is deprecated!

### ISSUE THREAD

**Issue by Dashon-Hawkins** [denji/homebrew-nginx#336]
### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/denji/homebrew-nginx/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.
****

**Comment by denji** [comment]
https://github.com/denji/homebrew-nginx/commit/bc8481f906cca34153e4a5a011628381e32825bc
