### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yangyu2010** [denji/homebrew-nginx#349]
brew install nginx-full --with-rtmp-module
==> Installing nginx-full from denji/nginx
==> Downloading https://nginx.org/download/nginx-1.14.0.tar.gz
Already downloaded: /Users/yangyu/Library/Caches/Homebrew/nginx-full-1.14.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nginx-full/1.14.0 --with-http_ssl_mod
==> make install
Last 15 lines from /Users/yangyu/Library/Logs/Homebrew/nginx-full/02.make:
    tp->ngx_tm_wday = (ngx_tm_wday_t) wday;
    ~~^
src/os/unix/ngx_time.h:19:16: note: forward declaration of 'struct tm'
typedef struct tm             ngx_tm_t;
               ^
src/core/ngx_times.c:436:16: error: variable has incomplete type 'struct tm'
    struct tm  tm;
               ^
src/os/unix/ngx_time.h:19:16: note: forward declaration of 'struct tm'
typedef struct tm             ngx_tm_t;
               ^
15 errors generated.
make[1]: *** [objs/src/core/ngx_times.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/denji/homebrew-nginx/issues

These open issues may also help:

**Comment by denji** [comment]
brew up
brew install nginx-full --with-rtmp-module

**Comment by denji** [comment]
I will close this problem if you still have problems please report here.
