### ISSUE TITLE
help

### ISSUE THREAD

**Issue by holoto** [denji/homebrew-nginx#351]
`==> make install
Last 15 lines from /Users/holoto/Library/Logs/Homebrew/nginx-full/02.make:
        encoder->flags |= CODEC_FLAG_GLOBAL_HEADER;             // make the codec generate the extra data
                          ^
clang -c -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Wno-deprecated-declarations -Werror -g -I/usr/local/include -I/usr/local/opt/pcre/include -I/usr/local/opt/openssl/include -D_LARGEFILE_SOURCE -DBUILDING_NGINX -I/usr/local/share/rtmp-nginx-module  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I /usr/local/share/rtmp-nginx-module -I /usr/include/libxml2 -I src/stream \
		-o objs/addon/vod-nginx-module/ngx_file_reader.o \
		/usr/local/share/vod-nginx-module/ngx_file_reader.c
clang -c -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Wno-deprecated-declarations -Werror -g -I/usr/local/include -I/usr/local/opt/pcre/include -I/usr/local/opt/openssl/include -D_LARGEFILE_SOURCE -DBUILDING_NGINX -I/usr/local/share/rtmp-nginx-module  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I /usr/local/share/rtmp-nginx-module -I /usr/include/libxml2 -I src/stream \
		-o objs/addon/vod-nginx-module/ngx_http_vod_conf.o \
		/usr/local/share/vod-nginx-module/ngx_http_vod_conf.c
/usr/local/share/vod-nginx-module/vod/filters/audio_encoder.c:142:45: error: use of undeclared identifier 'CODEC_CAP_VARIABLE_FRAME_SIZE'
        if ((state->encoder->codec->capabilities & CODEC_CAP_VARIABLE_FRAME_SIZE) != 0)
                                                   ^
2 errors generated.
make[1]: *** [objs/addon/filters/audio_encoder.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/denji/homebrew-nginx/issues

These open issues may also help:
Compiler error when installing nginx-full ---with-upload-module https://github.com/denji/homebrew-nginx/issues/304
building nginx-full with healthcheck module giving error https://github.com/denji/homebrew-nginx/issues/263
`

**Comment by denji** [comment]
https://github.com/kaltura/nginx-vod-module#dependencies

* Thumbnail capture & volume map - depend on ffmpeg (3.0 or newer)
( Audio filtering (for changing playback rate / gain) - depends on ffmpeg (3.0 or newer) and also on libfdk_aac. Due to licensing issues, libfdk_aac is not built into kaltura ffmpeg packages
* Encryption / decryption (DRM / HLS AES) - depends on openssl
* DFXP captions - depends on libxml2
* UTF-16 encoded SRT files - depends on iconv

**Comment by denji** [comment]
@holoto Did you fix the problem?

**Comment by holoto** [comment]
yes
