### ISSUE TITLE
denji.github.io/homebrew-nginx: needs minor update

### ISSUE THREAD

**Issue by marc-medley** [denji/homebrew-nginx#354]
https://denji.github.io/homebrew-nginx/, which is referenced in the top level repository description,  needs `brew tap homebrew/nginx` to be updated to `brew tap denji/nginx` (or possibly `brew tap [--full] denji/nginx`)

**Comment by denji** [comment]
https://github.com/denji/homebrew-nginx/commit/3433bfa83f32b4b56f1b2132d9c90fbe21e983d2
