### ISSUE TITLE
When building using --with-headers-more-module the module is not created / available

### ISSUE THREAD

**Issue by ahorseman** [denji/homebrew-nginx#358]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?

### Brief summary of issue:
I've tried on two machines building nginx with the --with-headers-more-module option, to get the headers more module which I try to include via
`load_module modules/ngx_http_headers_more_filter_module.so;`
in nginx.conf.
Yet, nginx complains that the file does not exist and I don't see any "modules" directory in the nginx installation path.
A find for the file (or any .so) does not return anything.

#### The complete command that you issued:
`brew install --verbose nginx-full --with-headers-more-module`

#### Gist with output of command issued:
https://gist.github.com/ahorseman/673ac3aa44d5d0a1fa7b1cbaaa164d7d

#### Output of `brew config`:
```
HOMEBREW_VERSION: 1.8.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdd8e9b7cf1e53322492e1e90f685c19bdfde506
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 898630216affffe6236cd9e97d4fd6efc595300c
Core tap last commit: 28 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit nehalem
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0
```

**Comment by denji** [comment]
We still use static linking modules. `load_module` may not even be used, dynamic loading issue #168.
