### ISSUE TITLE
mv: nginx.xsc: No such file or directory while installing nginx-full --with-perl

### ISSUE THREAD

**Issue by donysukardi** [denji/homebrew-nginx#361]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
```
$ brew install nginx-full --with-perl
==> Installing nginx-full from denji/nginx
==> Downloading https://nginx.org/download/nginx-1.15.8.tar.gz
Already downloaded: /Users/donysukardi/Library/Caches/Homebrew/downloads/58d1c431456260ff6b102d21e73f44a3118a03a05331cdfa4427e2eadeaa2871--nginx-1.15.8.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nginx-full/1.15.8 --with-http_ssl_module --with-pcre --with-ipv6 --sbin-path=/usr/local/Cellar/nginx-full/1.15.8/b
==> make install
Last 15 lines from /Users/donysukardi/Library/Logs/Homebrew/nginx-full/02.make:
mv nginx.xsc nginx.c
mv nginx.xsc nginx.c
cc -c  -I ../../../../../src/core -I ../../../../../src/event -I ../../../../../src/event/modules -I ../../../../../src/os/unix -I ../../../../../objs -I ../../../../../src/http -I ../../../../../src/http/modules -I ../../../../../src/http/modules/perl -fno-common -DPERL_DARWIN -mmacosx-version-min=10.14 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV -I/usr/local/Cellar/perl/5.28.1/lib/perl5/5.28.1/darwin-thread-multi-2level/CORE -g -I/usr/local/include -I/usr/local/opt/pcre/include -I/usr/local/opt/openssl/include -O   -DVERSION=\"1.15.8\" -DXS_VERSION=\"1.15.8\"  "-I/usr/local/Cellar/perl/5.28.1/lib/perl5/5.28.1/darwin-thread-multi-2level/CORE"   nginx.c
mv: nginx.xsc: No such file or directory
make[2]: *** [nginx.c] Error 1
make[1]: *** [install_perl_modules] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from nginx.xs:13:
../../../../../src/http/modules/perl/ngx_http_perl_module.h:17:10: fatal error: 'EXTERN.h' file not found
#include <EXTERN.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [nginx.o] Error 1
make[1]: *** [objs/src/http/modules/perl/blib/arch/auto/nginx/nginx.bundle] Error 2
make: *** [install] Error 2
```

#### Brief summary of issue:
I'm getting the above error while running `brew install nginx-full --with-perl`

#### The complete command that you issued:
`brew install nginx-full --with-perl`

#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/9344201e56a35d0f5d2a98ef72f4acd3

#### Output of `brew config`:
```
HOMEBREW_VERSION: 1.9.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7be9ac1e9d550df18392550d611c5ff10b91292b
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9d1020af324877a70bdadb3d2debbf0a426edfab
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /Users/donysukardi/Library/Logs/Homebrew
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_131
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```

**Comment by denji** [comment]
$ brew install perl
$ brew install nginx-full --with-perl

**Comment by donysukardi** [comment]
@denji thanks. i did exactly that and am still getting some error. any idea what i might be missing out?

with `--HEAD`
![image](https://user-images.githubusercontent.com/410792/51512020-b2ea0e80-1e3e-11e9-8e22-60df64c2952e.png)

without `--HEAD`
![image](https://user-images.githubusercontent.com/410792/51512062-f6dd1380-1e3e-11e9-8abf-338850fa60fb.png)

**Comment by denji** [comment]
The problem seems to be that we shouldn't use system perl. Since we need use userland Homebrew.

**Comment by arodionova** [comment]
@denji any updates on this issue?

**Comment by JParkinson1991** [comment]
Can confirm that this is not working for me either, even when installing perl via homebrew prior to installation.

**Comment by issenn** [comment]
[Common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems)

When running Mojave or higher (10.14+) you will also [need to install the additional SDK headers](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624) by downloading them from [Apple Developers](https://developer.apple.com/download/more/?q=Command%20Line%20Tools). You can also check under `/Library/Developer/CommandLineTools/Packages/` as some versions of Mac OS will have the `pkg` locally.
```
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```

[Xcode 10 Release Notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624)  
 In a future release, this package will no longer be provided.
