### ISSUE TITLE
Update 'dav-ext-nginx-module.rb' from v0.1.0 to v3.0.0

### ISSUE THREAD

**Issue by marc-medley** [denji/homebrew-nginx#362]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

Builds OK. ['dav-ext-nginx-module.rb'](https://github.com/denji/homebrew-nginx/blob/master/Formula/dav-ext-nginx-module.rb) is an out-of-date version which does not support macOS Finder native WebDAV (`WebDAVFS`) for both read & write.

#### Brief summary of issue:

['dav-ext-nginx-module.rb'](https://github.com/denji/homebrew-nginx/blob/master/Formula/dav-ext-nginx-module.rb) uses ['nginx-dav-ext-module' release](https://github.com/arut/nginx-dav-ext-module/releases) v.0.1.0 from Jul 16, 2017 which only supports WebDAV `PROPFIND` and `OPTIONS` methods.

The ['nginx-dav-ext-module' release ](https://github.com/arut/nginx-dav-ext-module/releases) v.3.0.0 from Dec 17, 2018 is significant becase. in addition to the WebDAV `PROPFIND` and `OPTIONS` methods, v3.0.0 also provides the `LOCK` and `UNLOCK` methods.

macOS Finder native WebDAV (`WebDAVFS`) expects these locking methods for a read/write sharepoint mount.

_The ['nginx-dav-ext-module' README Example 3](https://github.com/arut/nginx-dav-ext-module#example-3) shows a configuration of "WebDAV with locking which works with MacOS client"._

#### The complete command that you issued:

I am working with a brew nginx-full module configuration similar to Ubuntu's apt-get nginx-full:

``` bash
brew install nginx-full \
    --with-debug \
    --with-addition \
    --with-auth-req \
    --with-webdav \
    --with-dav-ext-module \
    --with-gunzip \
    --with-gzip-static \
    --with-image-filter \
    --with-realip \
    --with-slice \
    --with-status \
    --with-sub \
    --with-subs-filter-module \
    --with-http2 \
    --with-xslt \
    --with-mail \
    --with-mail-ssl \
    --with-pcre-jit \
    --with-stream \
    --with-stream-ssl \
    --with-stream-ssl-preread \
    --with-auth-pam-module \
    --with-echo-module
```

However,  the two required modules for the WebDAV capabilities are just `--with-webdav` and `--with-dav-ext-module`.

The test is to use the macOS Finder menu: Go > Connect to server… > http://machine_name.local:8080/. (default port)

#### Gist with output of `brew doctor`:

``` bash
brew doctor
# Your system is ready to brew.
```

#### Link output by `brew gist-logs <formula>`:

…

#### Output of `brew config`:

``` bash
brew config 
# HOMEBREW_VERSION: 1.9.2
# ORIGIN: https://github.com/Homebrew/brew
# HEAD: 7be9ac1e9d550df18392550d611c5ff10b91292b
# Last commit: 9 days ago
# Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
# Core tap HEAD: 6841a6ec4b9052dec1e466580e42b1f0bc5d2323
# Core tap last commit: 14 hours ago
# HOMEBREW_PREFIX: /usr/local
# HOMEBREW_LOGS: /Users/ev/Library/Logs/Homebrew
# CPU: dual-core 64-bit penryn
# Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
# Clang: 10.0 build 1000
# Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
# Curl: 7.54.0 => /usr/bin/curl
# macOS: 10.13.6-x86_64
# CLT: 10.1.0.0.1.1539992718
# Xcode: 10.1
```

### Formula Requests:

Existing formula which could benefit from a version update.

**Comment by denji** [comment]
https://github.com/denji/homebrew-nginx/commit/094225518d1d1cb9f3234ee84dda080b7cdad622

**Comment by marc-medley** [comment]
@denji FYI: I did a simple test/check of the update to `dav-ext-nginx-module.rb`.  The updated (uninstalled/reinstalled) brew nginx-full WebDAV did successfully mount using the native macOS Finder with _read/write_ permissions. Thanks.

Related, an update of [**https://denji.github.io/homebrew-nginx/**](https://denji.github.io/homebrew-nginx/) Modules list from _"dav-ext | 0.1.0"_ to something like _"dav-ext | 3.0.0 | Build with HTTP WebDav Extended PROPFIND OPTIONS LOCK UNLOCK support"_ would help others know that the current version available with `nginx-full`.
