### ISSUE TITLE
MethodDeprecatedError: Calling MacOS.prefer_64_bit? is disabled! There is no replacement.

### ISSUE THREAD

**Issue by SteveWebster66** [denji/homebrew-nginx#364]
Running on macos High Sierra 10.13.8

brew install openresty/brew/openresty

brew install openresty/brew/openresty
==> Installing openresty from openresty/brew
==> Installing dependencies for openresty/brew/openresty: openresty/brew/openresty-openssl and geoip
==> Installing openresty/brew/openresty dependency: openresty/brew/openresty-openssl
==> Downloading https://www.openssl.org/source/openssl-1.1.0h.tar.gz
Already downloaded: xxxxxxxx-openssl-1.1.0h.tar.gz
==> Downloading https://raw.githubusercontent.com/openresty/openresty/master/patches/openssl-1.1.0d-sess_set_get_cb_yield.patch
Already downloaded: xxxxxxx .  --openssl-1.1.0d-sess_set_get_cb_yield.patch
==> Patching
==> Applying openssl-1.1.0d-sess_set_get_cb_yield.patch
patching file include/openssl/bio.h
Hunk #1 succeeded at 217 (offset -3 lines).
patching file include/openssl/ssl.h
Hunk #1 succeeded at 812 (offset 21 lines).
Hunk #2 succeeded at 821 (offset 21 lines).
Hunk #3 succeeded at 1054 (offset 21 lines).
Hunk #4 succeeded at 1461 with fuzz 1 (offset 31 lines).
patching file ssl/bio_ssl.c
Hunk #1 succeeded at 139 (offset 1 line).
Hunk #2 succeeded at 215 (offset 1 line).
Hunk #3 succeeded at 372 (offset 1 line).
patching file ssl/ssl_lib.c
Hunk #1 succeeded at 3177 (offset 195 lines).
patching file ssl/ssl_sess.c
Hunk #2 succeeded at 512 (offset 8 lines).
Hunk #3 succeeded at 901 (offset 9 lines).
patching file ssl/statem/statem.c
Hunk #1 succeeded at 591 (offset 8 lines).
Hunk #2 succeeded at 622 (offset 8 lines).
patching file ssl/statem/statem.h
patching file ssl/statem/statem_srvr.c
Hunk #1 succeeded at 1147 (offset -18 lines).
patching file util/libssl.num
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling MacOS.prefer_64_bit? is disabled! There is no replacement.
Please report this to the openresty/brew tap:
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/openresty-openssl.rb:53

Tried uninstalling / reinstalling openssl but same error.

Looks like openresty-openssl.rb:53 should use: MacOS.is_64_bit?

Not the deprecated MacOS.prefer_64_bit

**Comment by denji** [comment]
https://formulae.brew.sh/formula/openssl

`brew install openresty/brew/openresty` != `brew install denji/openresty`

**Comment by denji** [comment]
https://github.com/openresty/homebrew-brew/blob/master/Formula/openresty.rb

https://github.com/openresty/homebrew-brew/issues

**Comment by jteppinette** [comment]
@denji I also get this error when installing the correct repo.

```
==> Installing openresty from denji/nginx
==> Installing dependencies for denji/nginx/openresty: denji/nginx/openresty-openssl and geoip
==> Installing denji/nginx/openresty dependency: denji/nginx/openresty-openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2k.tar.gz
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/openresty/openresty/master/patches/openssl-1.0.2h-sess_set_get_cb_yi
######################################################################## 100.0%
==> Patching
==> Applying openssl-1.0.2h-sess_set_get_cb_yield.patch
patching file ssl/s3_srvr.c
Hunk #3 succeeded at 1057 (offset 1 line).
patching file ssl/ssl3.h
patching file ssl/ssl.h
patching file ssl/ssl_lib.c
Hunk #1 succeeded at 2707 (offset -2 lines).
patching file ssl/ssl_locl.h
Hunk #1 succeeded at 524 (offset 6 lines).
patching file ssl/ssl_sess.c
patching file ssl/ssl_stat.c
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling MacOS.prefer_64_bit? is disabled! There is no replacement.
Please report this to the denji/nginx tap:
  /usr/local/Homebrew/Library/Taps/denji/homebrew-nginx/Formula/openresty-openssl.rb:42
```
