### ISSUE TITLE
I need an nginx module. https://www.nginx.com/resources/wiki/modules/concat/

### ISSUE THREAD

**Issue by jianfan0709** [denji/homebrew-nginx#368]
Hello,My Chinese name is Jiang Fan and my English name is rena.
I don't know how to write it [my-new-formula.rb] .
I need an nginx module.
url:https://www.nginx.com/resources/wiki/modules/concat/
Please tell me how to do it or you can help me finish it.
Thanks very much.

**Comment by denji** [comment]
https://github.com/alibaba/nginx-http-concat/issues

**Comment by jianfan0709** [comment]
Thanks very much.
