### ISSUE TITLE
brew reinstall nginx-full  with openssl@1.1

### ISSUE THREAD

**Issue by faloupy** [denji/homebrew-nginx#371]
Firstly, I appreciate your incredible work, thank you.

I''ve always built nginx from source, so that I can link against openssl 1.1.1.x to enable 0-RTT in TLSv1.3

However I recently needed a particular module and found nginx-full to be an amazing help, but it forces openssl 1.0.2s

after 
`brew install openssl@1.1 `
(first in my path. LDFLAGS, CPPFLAGS and PKG_CONFIG_PATH to their /usr/local/opt/openssl@1.1/ counterparts) 

Is there a way to pass an argument when reinstalling nginx-full to force dependency on openssl@1.1 or is the only realistic option to go back to building nginx from source? This is the only showstopper for me so far.

Thank you once again, I apologise if this is the wrong place to ask this question. I realise that in general 
`brew install (anything which depends on openssl)`
 will force openssl 1.0.2s.

**Comment by denji** [comment]
https://github.com/denji/homebrew-nginx/commit/b19244ed6f056298aeed4bc09e7ee072cf13a904
You can check it out.

**Comment by faloupy** [comment]
Thank you Denis,

It worked perfectly.

I found a few modules that didn’t build on either of my Mac’s and if that information would be useful I can add in a separate issue, once removed boom - TLS1.3 with 0-RTT

Thank you!

"Do not withhold good from those who need it, when you have the ability to help" - Proverbs 3.27 (NET)

**Comment by denji** [comment]
I'm glad to hear it, then I'm closing the deal. If you're having problems with your old Mac, open up a new issue. I don't have an apple ecosystem for testing anymore, except for travis-ci.

**Comment by Crypto-Victoria** [comment]
Привет, Денис @denji 
Нам в Сonnext оч нравится твой гит. Cвяжись с нами плиз если ты заинтересован в наёме или коллабе
