### ISSUE TITLE
macOS 10.15 install failed

### ISSUE THREAD

**Issue by monsterLin** [denji/homebrew-nginx#373]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
run `brew install nginx-full --with-rtmp-module`
```
Warning: You are using macOS 10.15.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this pre-release version.
```

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/denji/homebrew-nginx/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by denji** [comment]
You haven't described the details of the problem.
Have you installed XCode & Command Line Tools?
