### ISSUE TITLE
Warning: Calling plist_options is deprecated! Use service.require_root instead.

### ISSUE THREAD

**Issue by zouchengli** [denji/homebrew-nginx#420]
❯ brew upgrade
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the denji/nginx tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/denji/homebrew-nginx/Formula/nginx-full.rb:381

**Comment by amcgregor** [comment]
I've locally corrected and tested (service starts, listens to ports, responds as expected), with the caveat that I've marked the daemon to require root. The default configuration upon install listens to `8080`, but serving actual HTTP + HTTPS would be a common case. A warning might need to be emitted to verify the configuration? And specify default chuid user + group? (`nobody`+`staff`?)
