### ISSUE TITLE
Wrong url in the formula mp4-h264-nginx-module.rb

### ISSUE THREAD

**Issue by viaregio** [denji/homebrew-nginx#430]
I had to replace the url `http://h264.code-shop.com/download/nginx_mod_h264_streaming-2.2.7.tar.gz` with `https://github.com/code-shop-com/h264/raw/main/download/nginx_mod_h264_streaming-2.2.7.tar.gz` to get it working again.

**Comment by denji** [comment]
`https://github.com/code-shop-com/h264/raw/main/download/nginx_mod_h264_streaming-2.2.7.tar.gz` untagged git master version

**Comment by viaregio** [comment]
Maybe this isn't the right value for the url but it is momentarily working. Using the original url gives me a 404 error.
